### ISSUE TITLE
How to add waves?

### ISSUE THREAD

**Issue by ldd289806329** [mikafabricius/LumpedMassSpring_Umbilical_model#2]
Thank you very much for your Simulink model. I now know how to use it, but I have a question. how to use the waves? What is the model like? How to add the influence of waves? What is the size of this matrix? In your model, waves are zero (k, 3). If the influence of waves is applied, what is the appropriate size? Do you have any suggestions? Or where can I get the magnitude of this wave force?

**Comment by mikafabricius** [comment]
Hi again,

I will suppose that you know about wave theory, regular and irregular waves. So I will focus on how to incorporate them in my function. What you would need is the Morison equation, this will create forces in x, y and z (depending on your case, this could be simplified). This means that you will use the waves that you have from your wave theory, could be a JONSWAP spectrum. Then you would take the current node positions in the z coordinate, use this with your wave model, to find the velocities of the water at all of the different node positions. The velocities at the node positions, would then be used in the Morison equation, to find the corresponding forces exerted by the waves, at the specific node depths.
So you now have forces in x, and z, exerted by the waves at each of the node positions, so this gives the (k,3) matrix.

When you are done with you project, feel free to share it with me, I would be interested in reading your work.

Best regards,
Mika Fabricius
